#!/bin/bash

echo "📱 Stilya 開発用ビルド作成ガイド"
echo "================================"
echo ""
echo "このプロジェクトにはカスタムネイティブモジュールが含まれているため、"
echo "開発用ビルドの作成を推奨します。"
echo ""
echo "🎯 開発用ビルドの利点："
echo "- QRコードでアプリを起動"
echo "- すべての機能が使用可能"
echo "- Fast Refreshで即座に変更を反映"
echo "- Apple Developer Account不要（シミュレーター）"
echo ""
echo "📋 手順："
echo ""
echo "1️⃣ 開発用ビルドを作成（シミュレーター用）"
echo "   eas build --profile development --platform ios --local"
echo ""
echo "2️⃣ または実機用（要Apple Developer Account）"
echo "   eas build --profile development --platform ios"
echo ""
echo "3️⃣ ビルドが完了したら"
echo "   - シミュレーター: 自動的にインストール"
echo "   - 実機: QRコードからインストール"
echo ""
echo "4️⃣ 開発サーバーを起動"
echo "   npx expo start --dev-client"
echo ""
echo "5️⃣ アプリ内でQRコードをスキャン"
echo "   開発用ビルドのアプリ内でQRコードをスキャンして接続"
echo ""
echo "⚠️ 初回のみビルドが必要です（20-30分）"
echo "その後は通常のExpo開発と同じ体験です！"
echo ""
echo "💡 今すぐ始めるには："
echo "1. まずExpo Goで試す: npx expo start"
echo "2. 制限がある場合は開発用ビルドを作成"
