// eslint.config.js
module.exports = [
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        __DEV__: 'readonly',
        window: 'readonly',
        global: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        jest: 'readonly',
        describe: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
    rules: {
      // Disable problematic rules for MVP development
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'no-console': 'off',
      'prefer-const': 'warn',
      'no-var': 'error',
    },
  },
  {
    // Ignore specific files and directories
    ignores: [
      'node_modules/**',
      '.expo/**',
      'dist/**',
      'build/**',
      'android/**',
      'ios/**',
      'web-build/**',
      '*.config.js',
      '*.config.ts',
      'babel.config.js',
      'metro.config.js',
      'jest.config.js',
      'TestConnection*.tsx',
      'TestApp.js',
      'app.config.ts',
      'expo-env.d.ts',
      '**/*.d.ts',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.bak',
      '**/*.backup',
      'scripts/**',
      'patches/**',
      'backups/**',
      'patch-*.js',
      'fix-*.js',
      'setup*.js',
      'direct-*.js',
      'github-actions-*.js',
      'src/__tests__/**',
      'src/__mocks__/**',
      '**/*.ts',
      '**/*.tsx',
    ],
  },
];
