#!/bin/bash

echo "📱 iPhone実機登録ガイド"
echo "======================="

echo ""
echo "🔌 実機を接続する手順："
echo ""
echo "1️⃣ iPhoneをUSBケーブルでMacに接続"
echo "   - 純正ケーブルまたはMFi認証ケーブルを使用"
echo "   - iPhoneで「このコンピュータを信頼」をタップ"
echo ""
echo "2️⃣ Xcodeでデバイスを確認"
echo "   - Window → Devices and Simulators"
echo "   - 接続したiPhoneが表示されるまで待つ"
echo ""
echo "3️⃣ デバイスの登録"
echo "   - Xcodeが自動的にデバイスを登録"
echo "   - 初回は数分かかる場合があります"
echo ""
echo "4️⃣ プロジェクトで再度ビルド"
echo "   - Xcodeの上部バーで実機を選択"
echo "   - ▶️ ボタンでビルド開始"
echo ""

# 接続されているデバイスを確認
echo "🔍 現在接続されているデバイス："
system_profiler SPUSBDataType | grep -A 2 -i iphone || echo "iPhoneが検出されません"

echo ""
echo "📝 トラブルシューティング："
echo ""
echo "• デバイスが認識されない場合："
echo "  - USBケーブルを変更"
echo "  - 別のUSBポートを試す"
echo "  - iPhoneを再起動"
echo ""
echo "• 「信頼されていない開発者」エラー："
echo "  iPhone: 設定 → 一般 → VPNとデバイス管理"
echo "  → デベロッパAPP → 信頼"
echo ""
echo "✅ 実機が登録されたら："
echo "  cd /Users/koki_air/Documents/GitHub/Stilya"
echo "  npx expo run:ios --device"
