#!/bin/bash

# Stilya - iOSシミュレーターランタイムインストールガイド

echo "================================================"
echo "📱 iOSシミュレーターランタイムのインストール手順"
echo "================================================"
echo ""
echo "現在、iOSシミュレーターのランタイムがインストールされていません。"
echo "以下の手順でインストールしてください："
echo ""
echo "1️⃣ Xcodeを開く"
echo "   - Finderで「アプリケーション」フォルダを開く"
echo "   - 「Xcode」をダブルクリック"
echo ""
echo "2️⃣ 設定を開く"
echo "   - メニューバーで「Xcode」→「Settings...」を選択"
echo "   - または「Cmd + ,」を押す"
echo ""
echo "3️⃣ Platformsタブを選択"
echo "   - 設定ウィンドウで「Platforms」タブをクリック"
echo ""
echo "4️⃣ iOSランタイムをダウンロード"
echo "   - 「+」ボタンをクリック"
echo "   - 「iOS」を選択"
echo "   - 最新のiOS（例：iOS 18.2）を選んで「Download」"
echo "   - ダウンロードサイズ：約8GB"
echo ""
echo "5️⃣ ダウンロード完了を待つ"
echo "   - ダウンロードには時間がかかります（10-30分程度）"
echo "   - 完了したら設定ウィンドウを閉じる"
echo ""
echo "================================================"
echo ""
echo "💡 代替案："
echo "1. Expo Goアプリを使用（実機でテスト）"
echo "   - App StoreからExpo Goをダウンロード"
echo "   - npm start でQRコードを表示"
echo "   - iPhoneのカメラでQRコードをスキャン"
echo ""
echo "2. 実機でUSB接続してテスト"
echo "   - 開発者モードを有効化"
echo "   - USB接続して実行"
echo ""
echo "================================================"
echo ""
read -p "Xcodeを開いてランタイムをインストールしますか？ (y/n): " open_xcode

if [ "$open_xcode" = "y" ] || [ "$open_xcode" = "Y" ]; then
    echo "Xcodeを開いています..."
    open -a Xcode
    echo ""
    echo "上記の手順に従ってiOSランタイムをインストールしてください。"
    echo "インストール完了後、再度 ./start-ios-local.sh を実行してください。"
else
    echo ""
    echo "📱 Expo Goでテストする場合："
    echo "   npm start"
    echo ""
    echo "後でランタイムをインストールする場合："
    echo "   ./setup-ios-runtime.sh"
fi
