#!/bin/bash

echo "📱 Stilya QRコード開発ガイド"
echo "============================"

cd /Users/koki_air/Documents/GitHub/Stilya

echo ""
echo "🎯 2つの開発方法があります："
echo ""
echo "1️⃣ Expo Go を使った開発（QRコード）"
echo "   - Expo Goアプリが必要"
echo "   - QRコードをスキャンして実行"
echo "   - ネイティブ機能に制限あり"
echo ""
echo "2️⃣ ネイティブビルド（現在の方法）"
echo "   - Xcodeでビルド"
echo "   - すべての機能が使用可能"
echo "   - Apple Developer Account必要"
echo ""

echo "📱 QRコードで開発を始める方法："
echo "================================"
echo ""
echo "1. Expo Goアプリをインストール"
echo "   - App Storeで「Expo Go」を検索"
echo "   - iPhoneにインストール"
echo ""
echo "2. 開発サーバーを起動"
echo "   npx expo start"
echo ""
echo "3. QRコードをスキャン"
echo "   - Expo Goアプリでスキャン"
echo "   - またはカメラアプリでスキャン"
echo ""

# 実際に起動してみる
echo "🚀 開発サーバーを起動しています..."
echo ""
echo "実行コマンド:"
echo "npx expo start"
echo ""
echo "起動後の操作:"
echo "- 「s」キー: QRコードを表示/非表示"
echo "- 「r」キー: アプリをリロード"
echo "- 「m」キー: メニューを表示"
echo "- 「w」キー: Webブラウザで開く"
echo ""
echo "⚠️ 注意事項:"
echo "- iPhoneとMacが同じWi-Fiネットワークに接続されている必要があります"
echo "- VPNを使用している場合は無効にしてください"
echo ""
echo "💡 もしExpo Goで制限がある場合は、開発用ビルドを作成できます:"
echo "eas build --profile development --platform ios"
