// Database types generated by Supabase CLI
// Run `npm run supabase:types` to regenerate this file

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          nickname: string | null
          gender: 'male' | 'female' | 'other' | null
          age_range: string | null
          style_preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          nickname?: string | null
          gender?: 'male' | 'female' | 'other' | null
          age_range?: string | null
          style_preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          nickname?: string | null
          gender?: 'male' | 'female' | 'other' | null
          age_range?: string | null
          style_preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
      external_products: {
        Row: {
          id: string
          external_id: string
          source: 'linkshare' | 'a8net' | 'rakuten' | 'manual'
          name: string
          brand: string | null
          description: string | null
          price: number | null
          currency: string
          image_url: string
          product_url: string
          affiliate_url: string | null
          category: string | null
          subcategory: string | null
          tags: string[]
          gender: 'male' | 'female' | 'unisex' | null
          color: string | null
          size_info: Json
          metadata: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          external_id: string
          source: 'linkshare' | 'a8net' | 'rakuten' | 'manual'
          name: string
          brand?: string | null
          description?: string | null
          price?: number | null
          currency?: string
          image_url: string
          product_url: string
          affiliate_url?: string | null
          category?: string | null
          subcategory?: string | null
          tags?: string[]
          gender?: 'male' | 'female' | 'unisex' | null
          color?: string | null
          size_info?: Json
          metadata?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          external_id?: string
          source?: 'linkshare' | 'a8net' | 'rakuten' | 'manual'
          name?: string
          brand?: string | null
          description?: string | null
          price?: number | null
          currency?: string
          image_url?: string
          product_url?: string
          affiliate_url?: string | null
          category?: string | null
          subcategory?: string | null
          tags?: string[]
          gender?: 'male' | 'female' | 'unisex' | null
          color?: string | null
          size_info?: Json
          metadata?: Json
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      swipes: {
        Row: {
          id: string
          user_id: string
          product_id: string
          direction: 'yes' | 'no' | 'skip'
          session_id: string | null
          swiped_at: string
        }
        Insert: {
          id?: string
          user_id: string
          product_id: string
          direction: 'yes' | 'no' | 'skip'
          session_id?: string | null
          swiped_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          product_id?: string
          direction?: 'yes' | 'no' | 'skip'
          session_id?: string | null
          swiped_at?: string
        }
      }
      favorites: {
        Row: {
          id: string
          user_id: string
          product_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          product_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          product_id?: string
          created_at?: string
        }
      }
      click_logs: {
        Row: {
          id: string
          user_id: string | null
          product_id: string | null
          action: 'view' | 'click' | 'purchase'
          session_id: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          product_id?: string | null
          action: 'view' | 'click' | 'purchase'
          session_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          product_id?: string | null
          action?: 'view' | 'click' | 'purchase'
          session_id?: string | null
          metadata?: Json
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}